import { Roboto } from "next/font/google";

import "@/app/globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

import { config } from "@/providers/wagmiConfig";
import RainbowProvider from "@/providers/RainbowProvider";

import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import Web3Providers from "@/web3/providers";

const roboto = Roboto({
   subsets: ["latin"],
   weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
   title: "Inclusive DeFi",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   const initialState = cookieToInitialState(config, headers().get("cookie"));

   return (
      <html lang="en" className="light">
         <body className={cn("min-h-svh bg-background", roboto.className)}>
            <RainbowProvider initialState={initialState}>
               <Web3Providers>
                  <Toaster richColors position="top-right" />
                  {children}
               </Web3Providers>
            </RainbowProvider>
         </body>
      </html>
   );
}
